"""initial schema

Revision ID: 68b659cb388d
Revises: 
Create Date: 2026-08-24 10:29:21.581504

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '68b659cb388d'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('data_stores',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('folder_path', sa.String(length=768), nullable=False),
    sa.Column('scan_pattern', sa.String(length=255), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('auto_process_enabled', sa.Boolean(), nullable=True),
    sa.Column('auto_process_interval_minutes', sa.Integer(), nullable=True),
    sa.Column('last_scan_at', sa.DateTime(), nullable=True),
    sa.Column('last_scan_status', sa.String(length=50), nullable=True),
    sa.Column('last_scan_error', sa.Text(), nullable=True),
    sa.Column('last_scan_total_files', sa.Integer(), nullable=True),
    sa.Column('last_scan_processed', sa.Integer(), nullable=True),
    sa.Column('last_scan_new', sa.Integer(), nullable=True),
    sa.Column('last_scan_modified', sa.Integer(), nullable=True),
    sa.Column('last_scan_skipped', sa.Integer(), nullable=True),
    sa.Column('last_scan_errors', sa.Integer(), nullable=True),
    sa.Column('last_event_processed', sa.Integer(), nullable=True),
    sa.Column('last_event_at', sa.DateTime(), nullable=True),
    sa.Column('last_recovered_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('folder_path')
    )
    op.create_index(op.f('ix_data_stores_id'), 'data_stores', ['id'], unique=False)
    op.create_index(op.f('ix_data_stores_is_active'), 'data_stores', ['is_active'], unique=False)
    op.create_table('organisations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('parent_id', sa.Integer(), nullable=True),
    sa.Column('path', sa.String(length=2048), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['parent_id'], ['organisations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_organisations_id'), 'organisations', ['id'], unique=False)
    op.create_index(op.f('ix_organisations_parent_id'), 'organisations', ['parent_id'], unique=False)
    op.create_table('user_profiles',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('org_id', sa.Integer(), nullable=True),
    sa.Column('preferences_json', sa.Text(), nullable=True),
    sa.Column('query_patterns_json', sa.Text(), nullable=True),
    sa.Column('domain_focus_json', sa.Text(), nullable=True),
    sa.Column('communication_style', sa.String(length=32), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'org_id', name='uq_user_profiles_user_org')
    )
    op.create_index(op.f('ix_user_profiles_org_id'), 'user_profiles', ['org_id'], unique=False)
    op.create_index(op.f('ix_user_profiles_user_id'), 'user_profiles', ['user_id'], unique=False)
    op.create_table('data_store_file_manifests',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('datastore_id', sa.Integer(), nullable=False),
    sa.Column('file_path', sa.String(length=767), nullable=False),
    sa.Column('file_hash', sa.String(length=64), nullable=False),
    sa.Column('file_size', sa.BigInteger(), nullable=False),
    sa.Column('file_mtime', sa.BigInteger(), nullable=True),
    sa.Column('discovered_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['datastore_id'], ['data_stores.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('datastore_id', 'file_path', name='uq_datastore_file_path')
    )
    op.create_index(op.f('ix_data_store_file_manifests_datastore_id'), 'data_store_file_manifests', ['datastore_id'], unique=False)
    op.create_index(op.f('ix_data_store_file_manifests_id'), 'data_store_file_manifests', ['id'], unique=False)
    op.create_index('ix_manifest_datastore_file_hash', 'data_store_file_manifests', ['datastore_id', 'file_hash'], unique=False)
    op.create_table('organization_data_stores',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('org_id', sa.Integer(), nullable=False),
    sa.Column('data_store_id', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('assigned_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['data_store_id'], ['data_stores.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['org_id'], ['organisations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('org_id', 'data_store_id', name='uq_org_datastore')
    )
    op.create_index(op.f('ix_organization_data_stores_id'), 'organization_data_stores', ['id'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('username', sa.String(length=255), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('role', sa.Enum('user', 'admin', 'super_admin', name='userrole'), server_default='user', nullable=False),
    sa.Column('org_id', sa.Integer(), nullable=True),
    sa.Column('token_version', sa.Integer(), server_default='0', nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['org_id'], ['organisations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_index(op.f('ix_users_org_id'), 'users', ['org_id'], unique=False)
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    op.create_table('abbreviation_lists',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('org_id', sa.Integer(), nullable=True),
    sa.Column('is_enabled', sa.Boolean(), nullable=False),
    sa.Column('row_count', sa.Integer(), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['org_id'], ['organisations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_abbreviation_lists_id'), 'abbreviation_lists', ['id'], unique=False)
    op.create_index(op.f('ix_abbreviation_lists_is_enabled'), 'abbreviation_lists', ['is_enabled'], unique=False)
    op.create_index(op.f('ix_abbreviation_lists_org_id'), 'abbreviation_lists', ['org_id'], unique=False)
    op.create_table('folders',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_folders_user_id'), 'folders', ['user_id'], unique=False)
    op.create_table('knowledge_bases',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', mysql.LONGTEXT(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('org_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['org_id'], ['organisations.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_knowledge_bases_id'), 'knowledge_bases', ['id'], unique=False)
    op.create_index(op.f('ix_knowledge_bases_org_id'), 'knowledge_bases', ['org_id'], unique=False)
    op.create_table('settings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('key', sa.String(length=128), nullable=False),
    sa.Column('scope', sa.String(length=8), nullable=False),
    sa.Column('org_id', sa.Integer(), nullable=True),
    sa.Column('value', sa.Text(), nullable=True),
    sa.Column('updated_by', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['org_id'], ['organisations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['updated_by'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_settings_scope', 'settings', ['scope'], unique=False)
    op.create_index(op.f('ix_settings_id'), 'settings', ['id'], unique=False)
    op.create_index(op.f('ix_settings_key'), 'settings', ['key'], unique=False)
    op.create_index('uq_org_key', 'settings', ['org_id', 'key'], unique=True)
    op.create_table('abbreviations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('list_id', sa.Integer(), nullable=False),
    sa.Column('abbreviation', sa.String(length=128), nullable=False),
    sa.Column('expanded_form', sa.String(length=1024), nullable=False),
    sa.Column('category', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['list_id'], ['abbreviation_lists.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_abbreviations_abbreviation'), 'abbreviations', ['abbreviation'], unique=False)
    op.create_index(op.f('ix_abbreviations_id'), 'abbreviations', ['id'], unique=False)
    op.create_index(op.f('ix_abbreviations_list_id'), 'abbreviations', ['list_id'], unique=False)
    op.create_table('chats',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('history_summary', mysql.LONGTEXT(), nullable=True),
    sa.Column('pinned', sa.Boolean(), server_default='0', nullable=False),
    sa.Column('folder_id', sa.Integer(), nullable=True),
    sa.Column('org_id', sa.Integer(), nullable=True),
    sa.Column('active_branches', mysql.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['folder_id'], ['folders.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['org_id'], ['organisations.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_chats_folder_id'), 'chats', ['folder_id'], unique=False)
    op.create_index(op.f('ix_chats_id'), 'chats', ['id'], unique=False)
    op.create_index(op.f('ix_chats_org_id'), 'chats', ['org_id'], unique=False)
    op.create_table('document_uploads',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('knowledge_base_id', sa.Integer(), nullable=False),
    sa.Column('file_name', sa.String(length=255), nullable=False),
    sa.Column('file_hash', sa.String(length=64), nullable=False),
    sa.Column('file_size', sa.BigInteger(), nullable=False),
    sa.Column('content_type', sa.String(length=100), nullable=False),
    sa.Column('temp_path', sa.String(length=1024), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('status', sa.String(length=50), server_default='pending', nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['knowledge_base_id'], ['knowledge_bases.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_document_uploads_created_at'), 'document_uploads', ['created_at'], unique=False)
    op.create_index(op.f('ix_document_uploads_id'), 'document_uploads', ['id'], unique=False)
    op.create_index(op.f('ix_document_uploads_status'), 'document_uploads', ['status'], unique=False)
    op.create_table('documents',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('file_path', sa.String(length=767), nullable=False),
    sa.Column('file_name', sa.String(length=512), nullable=False),
    sa.Column('file_size', sa.BigInteger(), nullable=False),
    sa.Column('content_type', sa.String(length=100), nullable=False),
    sa.Column('file_hash', sa.String(length=64), nullable=True),
    sa.Column('knowledge_base_id', sa.Integer(), nullable=True),
    sa.Column('data_store_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('modified_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['data_store_id'], ['data_stores.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['knowledge_base_id'], ['knowledge_bases.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('file_path', 'data_store_id', name='uq_document_file_path_datastore'),
    sa.UniqueConstraint('knowledge_base_id', 'file_name', name='uq_kb_file_name')
    )
    op.create_index(op.f('ix_documents_data_store_id'), 'documents', ['data_store_id'], unique=False)
    op.create_index(op.f('ix_documents_file_hash'), 'documents', ['file_hash'], unique=False)
    op.create_index(op.f('ix_documents_id'), 'documents', ['id'], unique=False)
    op.create_index(op.f('ix_documents_knowledge_base_id'), 'documents', ['knowledge_base_id'], unique=False)
    op.create_index(op.f('ix_documents_modified_at'), 'documents', ['modified_at'], unique=False)
    op.create_table('knowledge_base_datastores',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('knowledge_base_id', sa.Integer(), nullable=False),
    sa.Column('data_store_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['data_store_id'], ['data_stores.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['knowledge_base_id'], ['knowledge_bases.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('knowledge_base_id', 'data_store_id')
    )
    op.create_index(op.f('ix_knowledge_base_datastores_data_store_id'), 'knowledge_base_datastores', ['data_store_id'], unique=False)
    op.create_index(op.f('ix_knowledge_base_datastores_id'), 'knowledge_base_datastores', ['id'], unique=False)
    op.create_index(op.f('ix_knowledge_base_datastores_knowledge_base_id'), 'knowledge_base_datastores', ['knowledge_base_id'], unique=False)
    op.create_table('chat_knowledge_bases',
    sa.Column('chat_id', sa.Integer(), nullable=False),
    sa.Column('knowledge_base_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['chat_id'], ['chats.id'], ),
    sa.ForeignKeyConstraint(['knowledge_base_id'], ['knowledge_bases.id'], ),
    sa.PrimaryKeyConstraint('chat_id', 'knowledge_base_id')
    )
    op.create_table('document_chunks',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('kb_id', sa.Integer(), nullable=True),
    sa.Column('data_store_id', sa.Integer(), nullable=True),
    sa.Column('document_id', sa.Integer(), nullable=False),
    sa.Column('file_name', sa.String(length=255), nullable=False),
    sa.Column('chunk_text', mysql.LONGTEXT(), nullable=False),
    sa.Column('chunk_index', sa.Integer(), nullable=True),
    sa.Column('chunk_metadata', sa.JSON(), nullable=True),
    sa.Column('hash', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['data_store_id'], ['data_stores.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], ),
    sa.ForeignKeyConstraint(['kb_id'], ['knowledge_bases.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_kb_file_name', 'document_chunks', ['kb_id', 'file_name'], unique=False)
    op.create_index(op.f('ix_document_chunks_data_store_id'), 'document_chunks', ['data_store_id'], unique=False)
    op.create_index(op.f('ix_document_chunks_document_id'), 'document_chunks', ['document_id'], unique=False)
    op.create_index(op.f('ix_document_chunks_hash'), 'document_chunks', ['hash'], unique=False)
    op.create_table('messages',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('content', mysql.LONGTEXT(), nullable=False),
    sa.Column('role', sa.String(length=50), nullable=False),
    sa.Column('chat_id', sa.Integer(), nullable=False),
    sa.Column('parent_message_id', sa.Integer(), nullable=True),
    sa.Column('branch_index', sa.Integer(), server_default='0', nullable=False),
    sa.Column('confidence_level', sa.String(length=20), nullable=True),
    sa.Column('confidence_score', sa.Integer(), nullable=True),
    sa.Column('confidence_breakdown', mysql.LONGTEXT(), nullable=True),
    sa.Column('final_confidence', sa.Float(), nullable=True),
    sa.Column('final_confidence_level', sa.String(length=20), nullable=True),
    sa.Column('faithfulness', sa.Integer(), nullable=True),
    sa.Column('completeness', sa.Integer(), nullable=True),
    sa.Column('retrieval_score', sa.Integer(), nullable=True),
    sa.Column('rewritten_query', mysql.LONGTEXT(), nullable=True),
    sa.Column('last_answer_object', mysql.JSON(), nullable=True),
    sa.Column('plan', mysql.JSON(), nullable=True),
    sa.Column('tool_calls', mysql.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['chat_id'], ['chats.id'], ),
    sa.ForeignKeyConstraint(['parent_message_id'], ['messages.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_messages_id'), 'messages', ['id'], unique=False)
    op.create_index(op.f('ix_messages_parent_message_id'), 'messages', ['parent_message_id'], unique=False)
    op.create_table('processing_tasks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('knowledge_base_id', sa.Integer(), nullable=True),
    sa.Column('data_store_id', sa.Integer(), nullable=True),
    sa.Column('document_id', sa.Integer(), nullable=True),
    sa.Column('document_upload_id', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('progress', sa.Integer(), nullable=True),
    sa.Column('progress_message', sa.String(length=512), nullable=True),
    sa.Column('graph_status', sa.String(length=50), nullable=True),
    sa.Column('graph_error', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['data_store_id'], ['data_stores.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['document_upload_id'], ['document_uploads.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['knowledge_base_id'], ['knowledge_bases.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_processing_tasks_data_store_id'), 'processing_tasks', ['data_store_id'], unique=False)
    op.create_index(op.f('ix_processing_tasks_document_id'), 'processing_tasks', ['document_id'], unique=False)
    op.create_index(op.f('ix_processing_tasks_id'), 'processing_tasks', ['id'], unique=False)
    op.create_index(op.f('ix_processing_tasks_status'), 'processing_tasks', ['status'], unique=False)
    op.create_table('chat_files',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('chat_id', sa.Integer(), nullable=False),
    sa.Column('message_id', sa.Integer(), nullable=True),
    sa.Column('file_name', sa.String(length=255), nullable=False),
    sa.Column('stored_path', sa.String(length=1024), nullable=True),
    sa.Column('file_size', sa.BigInteger(), nullable=False),
    sa.Column('content_type', sa.String(length=100), nullable=False),
    sa.Column('markdown_content', sa.Text(), nullable=True),
    sa.Column('token_count', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['chat_id'], ['chats.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['message_id'], ['messages.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_chat_files_chat_id'), 'chat_files', ['chat_id'], unique=False)
    op.create_index(op.f('ix_chat_files_message_id'), 'chat_files', ['message_id'], unique=False)
    op.create_table('clarification_requests',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('chat_id', sa.Integer(), nullable=False),
    sa.Column('assistant_message_id', sa.Integer(), nullable=False),
    sa.Column('question', sa.Text(), nullable=False),
    sa.Column('options', sa.JSON(), nullable=True),
    sa.Column('rationale', sa.Text(), nullable=True),
    sa.Column('user_response', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=20), server_default='pending', nullable=False),
    sa.Column('attempt', sa.Integer(), server_default='1', nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('answered_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['assistant_message_id'], ['messages.id'], ),
    sa.ForeignKeyConstraint(['chat_id'], ['chats.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_clarification_requests_assistant_message_id'), 'clarification_requests', ['assistant_message_id'], unique=False)
    op.create_index(op.f('ix_clarification_requests_chat_id'), 'clarification_requests', ['chat_id'], unique=False)
    op.create_table('message_citations',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('message_id', sa.Integer(), nullable=False),
    sa.Column('document_id', sa.Integer(), nullable=False),
    sa.Column('chunk_index', sa.Integer(), nullable=False),
    sa.Column('citation_index', sa.Integer(), nullable=False),
    sa.Column('citation_metadata', mysql.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['message_id'], ['messages.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_message_citations_message_id'), 'message_citations', ['message_id'], unique=False)
    op.create_table('tool_call_audit',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('chat_id', sa.Integer(), nullable=False),
    sa.Column('message_id', sa.Integer(), nullable=True),
    sa.Column('iteration', sa.Integer(), nullable=False),
    sa.Column('tool_name', sa.String(length=50), nullable=False),
    sa.Column('arguments', mysql.JSON(), nullable=True),
    sa.Column('result_summary', mysql.JSON(), nullable=True),
    sa.Column('tokens_in', sa.Integer(), nullable=False),
    sa.Column('tokens_out', sa.Integer(), nullable=False),
    sa.Column('latency_ms', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.CheckConstraint("status IN ('ok','error','denied','timeout','budget_exceeded')", name='tool_call_audit_status_check'),
    sa.ForeignKeyConstraint(['chat_id'], ['chats.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['message_id'], ['messages.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tool_call_audit_chat_id'), 'tool_call_audit', ['chat_id'], unique=False)
    op.create_index(op.f('ix_tool_call_audit_message_id'), 'tool_call_audit', ['message_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_tool_call_audit_message_id'), table_name='tool_call_audit')
    op.drop_index(op.f('ix_tool_call_audit_chat_id'), table_name='tool_call_audit')
    op.drop_table('tool_call_audit')
    op.drop_index(op.f('ix_message_citations_message_id'), table_name='message_citations')
    op.drop_table('message_citations')
    op.drop_index(op.f('ix_clarification_requests_chat_id'), table_name='clarification_requests')
    op.drop_index(op.f('ix_clarification_requests_assistant_message_id'), table_name='clarification_requests')
    op.drop_table('clarification_requests')
    op.drop_index(op.f('ix_chat_files_message_id'), table_name='chat_files')
    op.drop_index(op.f('ix_chat_files_chat_id'), table_name='chat_files')
    op.drop_table('chat_files')
    op.drop_index(op.f('ix_processing_tasks_status'), table_name='processing_tasks')
    op.drop_index(op.f('ix_processing_tasks_id'), table_name='processing_tasks')
    op.drop_index(op.f('ix_processing_tasks_document_id'), table_name='processing_tasks')
    op.drop_index(op.f('ix_processing_tasks_data_store_id'), table_name='processing_tasks')
    op.drop_table('processing_tasks')
    op.drop_index(op.f('ix_messages_parent_message_id'), table_name='messages')
    op.drop_index(op.f('ix_messages_id'), table_name='messages')
    op.drop_table('messages')
    op.drop_index(op.f('ix_document_chunks_hash'), table_name='document_chunks')
    op.drop_index(op.f('ix_document_chunks_document_id'), table_name='document_chunks')
    op.drop_index(op.f('ix_document_chunks_data_store_id'), table_name='document_chunks')
    op.drop_index('idx_kb_file_name', table_name='document_chunks')
    op.drop_table('document_chunks')
    op.drop_table('chat_knowledge_bases')
    op.drop_index(op.f('ix_knowledge_base_datastores_knowledge_base_id'), table_name='knowledge_base_datastores')
    op.drop_index(op.f('ix_knowledge_base_datastores_id'), table_name='knowledge_base_datastores')
    op.drop_index(op.f('ix_knowledge_base_datastores_data_store_id'), table_name='knowledge_base_datastores')
    op.drop_table('knowledge_base_datastores')
    op.drop_index(op.f('ix_documents_modified_at'), table_name='documents')
    op.drop_index(op.f('ix_documents_knowledge_base_id'), table_name='documents')
    op.drop_index(op.f('ix_documents_id'), table_name='documents')
    op.drop_index(op.f('ix_documents_file_hash'), table_name='documents')
    op.drop_index(op.f('ix_documents_data_store_id'), table_name='documents')
    op.drop_table('documents')
    op.drop_index(op.f('ix_document_uploads_status'), table_name='document_uploads')
    op.drop_index(op.f('ix_document_uploads_id'), table_name='document_uploads')
    op.drop_index(op.f('ix_document_uploads_created_at'), table_name='document_uploads')
    op.drop_table('document_uploads')
    op.drop_index(op.f('ix_chats_org_id'), table_name='chats')
    op.drop_index(op.f('ix_chats_id'), table_name='chats')
    op.drop_index(op.f('ix_chats_folder_id'), table_name='chats')
    op.drop_table('chats')
    op.drop_index(op.f('ix_abbreviations_list_id'), table_name='abbreviations')
    op.drop_index(op.f('ix_abbreviations_id'), table_name='abbreviations')
    op.drop_index(op.f('ix_abbreviations_abbreviation'), table_name='abbreviations')
    op.drop_table('abbreviations')
    op.drop_index('uq_org_key', table_name='settings')
    op.drop_index(op.f('ix_settings_key'), table_name='settings')
    op.drop_index(op.f('ix_settings_id'), table_name='settings')
    op.drop_index('idx_settings_scope', table_name='settings')
    op.drop_table('settings')
    op.drop_index(op.f('ix_knowledge_bases_org_id'), table_name='knowledge_bases')
    op.drop_index(op.f('ix_knowledge_bases_id'), table_name='knowledge_bases')
    op.drop_table('knowledge_bases')
    op.drop_index(op.f('ix_folders_user_id'), table_name='folders')
    op.drop_table('folders')
    op.drop_index(op.f('ix_abbreviation_lists_org_id'), table_name='abbreviation_lists')
    op.drop_index(op.f('ix_abbreviation_lists_is_enabled'), table_name='abbreviation_lists')
    op.drop_index(op.f('ix_abbreviation_lists_id'), table_name='abbreviation_lists')
    op.drop_table('abbreviation_lists')
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_index(op.f('ix_users_org_id'), table_name='users')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_organization_data_stores_id'), table_name='organization_data_stores')
    op.drop_table('organization_data_stores')
    op.drop_index('ix_manifest_datastore_file_hash', table_name='data_store_file_manifests')
    op.drop_index(op.f('ix_data_store_file_manifests_id'), table_name='data_store_file_manifests')
    op.drop_index(op.f('ix_data_store_file_manifests_datastore_id'), table_name='data_store_file_manifests')
    op.drop_table('data_store_file_manifests')
    op.drop_index(op.f('ix_user_profiles_user_id'), table_name='user_profiles')
    op.drop_index(op.f('ix_user_profiles_org_id'), table_name='user_profiles')
    op.drop_table('user_profiles')
    op.drop_index(op.f('ix_organisations_parent_id'), table_name='organisations')
    op.drop_index(op.f('ix_organisations_id'), table_name='organisations')
    op.drop_table('organisations')
    op.drop_index(op.f('ix_data_stores_is_active'), table_name='data_stores')
    op.drop_index(op.f('ix_data_stores_id'), table_name='data_stores')
    op.drop_table('data_stores')
    # ### end Alembic commands ###
