"""add expanded_query to messages

Revision ID: 741cf49c984c
Revises: 68b659cb388d
Create Date: 2026-08-24 11:18:27.173392

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '741cf49c984c'
down_revision: Union[str, None] = '68b659cb388d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('messages', sa.Column('expanded_query', mysql.LONGTEXT(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('messages', 'expanded_query')
    # ### end Alembic commands ###
