"""Add document authority fields

Revision ID: 78839807b756
Revises: j0e6f7a8b9c0
Create Date: 2026-09-08 19:58:00.011312

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '78839807b756'
down_revision: Union[str, None] = 'j0e6f7a8b9c0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('documents', sa.Column('document_status', sa.String(length=20), server_default=sa.text("'active'"), nullable=False))
    op.add_column('documents', sa.Column('effective_from', sa.DateTime(), server_default=sa.text("'1970-01-01 00:00:00'"), nullable=False))
    op.add_column('documents', sa.Column('effective_to', sa.DateTime(), nullable=True))
    op.add_column('documents', sa.Column('version', sa.String(length=50), server_default=sa.text("'1'"), nullable=False))
    op.add_column('documents', sa.Column('owner', sa.String(length=255), nullable=True))
    op.create_index(op.f('ix_documents_document_status'), 'documents', ['document_status'], unique=False)
    op.create_index(op.f('ix_documents_effective_from'), 'documents', ['effective_from'], unique=False)
    op.create_index(op.f('ix_documents_effective_to'), 'documents', ['effective_to'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_documents_effective_to'), table_name='documents')
    op.drop_index(op.f('ix_documents_effective_from'), table_name='documents')
    op.drop_index(op.f('ix_documents_document_status'), table_name='documents')
    op.drop_column('documents', 'owner')
    op.drop_column('documents', 'version')
    op.drop_column('documents', 'effective_to')
    op.drop_column('documents', 'effective_from')
    op.drop_column('documents', 'document_status')
    # ### end Alembic commands ###
